version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env


  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    ports:
      # - 127.0.0.1:8080:80
      # - 127.0.0.1:48916:80
      - 48916:80
    volumes:
      - nextcloud:/var/www/html
      # - ./config.php:/var/www/html/config/config.php
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      # - NEXTCLOUD_TRUSTED_DOMAINS="localhost 192.168.1.112 192.168.1.111 192.168.1.227"
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db

  # localtunnel:
  #   image: efrecon/localtunnel
  #   links:
  #     - app
  #   command:
  #     --local-host app --port 80

volumes:
  db:
  nextcloud: